apps/blog/urls.py
from django.urls import path

from apps.blog.views import BlogView, PostDetailView, BlogCategoryView

app_name = "blog"

urlpatterns = [
    path("", BlogView.as_view(), name="blog"),
    path("category/<slug:slug>/", BlogCategoryView.as_view(), name="blog-category"),
    path("<slug:slug>", PostDetailView.as_view(), name="post-detail"),
]

apps/shop/urls.py
from django.urls import path

from apps.shop.views import HomeView, ProductDetailView

app_name = "shop"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("<slug:slug>", ProductDetailView.as_view(), name="product-detail"),
]

project/urls.py
import debug_toolbar
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include(debug_toolbar.urls)),
    path("api/v1/", include("project.urls_api")),
    path("", include("apps.shop.urls")),
    path("blog/", include("apps.blog.urls")),
    path("membership/", include("apps.membership.urls")),
]

if settings.DEBUG:
    import mimetypes

    # fix javascript error
    mimetypes.add_type("application/javascript", ".js", True)

project/templates/partials/_footer.html
<footer class="text-muted py-5">
    <div class="container">
        <p class="float-end mb-1">
            <a href="#">Back to top</a>
        </p>
        <p class="mb-1">Album example is &copy; Bootstrap, but please download and customize it for yourself!
            {% if request.user.is_authenticated %}
                <a href="{% url 'membership:logout' %}">Logout</a>
            {% else %}
                <a href="{% url 'membership:login' %}">Login</a>
            {% endif %}
        </p>
    </div>
</footer>

project/templates/partials/_header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'shop:home' %}">Example portal</a>
        <button aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation"
                class="navbar-toggler"
                data-bs-target="#navbarNavDropdown" data-bs-toggle="collapse" type="button">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a aria-current="page"
                       class="nav-link {% if request.resolver_match.url_name == 'home' %}active{% endif %}"
                       href="{% url 'shop:home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a aria-current="page"
                       class="nav-link {% if request.resolver_match.url_name == 'blog' %}active{% endif %}"
                       href="{% url 'blog:blog' %}">Blog</a>
                </li>
            </ul>
        </div>
    </div>
</nav>