apps/blog/urls.py
from django.urls import path

from apps.blog.views import BlogView, PostDetailView, BlogCategoryView

app_name = "blog"

urlpatterns = [
    path("", BlogView.as_view(), name="blog"),
    path("category/<slug:slug>/", BlogCategoryView.as_view(), name="blog-category"),
    path("<slug:slug>", PostDetailView.as_view(), name="post-detail"),
]

project/urls.py
import debug_toolbar
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include(debug_toolbar.urls)),
    path("api/v1/", include("project.urls_api")),
    path("", include("apps.shop.urls")),
    path("blog/", include("apps.blog.urls")),
    path("membership/", include("apps.membership.urls")),
]

if settings.DEBUG:
    import mimetypes

    # fix javascript error
    mimetypes.add_type("application/javascript", ".js", True)

apps/blog/models.py
from django.db import models
from django_extensions.db.models import TitleSlugDescriptionModel, TimeStampedModel, ActivatorModel
from django.utils.translation import gettext as _


class Category(TitleSlugDescriptionModel):
    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")


class Post(TitleSlugDescriptionModel, TimeStampedModel, ActivatorModel):
    categories = models.ManyToManyField(Category, related_name="posts")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _("Post")
        verbose_name_plural = _("Posts")


class Comment(TimeStampedModel):
    post = models.ForeignKey(Post, related_name="comments", on_delete=models.CASCADE)
    author = models.CharField(max_length=255)
    text = models.TextField()

    def __str__(self):
        return self.author

    class Meta:
        verbose_name = _("Comment")
        verbose_name_plural = _("Comments")

apps/blog/forms.py
from django import forms

from apps.blog.models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = (
            "author",
            "text",
            "post",
        )
        widgets = {
            "post": forms.HiddenInput(),
        }

apps/blog/views.py
from django.db.models import Count
from django.urls import reverse
from django.views.generic import ListView, DetailView
from django.views.generic.edit import FormMixin

from apps.blog.forms import CommentForm
from apps.blog.models import Post, Category, Comment


class BlogView(ListView):
    template_name = "blog/blog.html"
    model = Post
    context_object_name = "posts"
    paginate_by = 6

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = Category.objects.annotate(posts_count=Count("posts")).filter(posts_count__gt=0)
        return context


class BlogCategoryView(BlogView):
    template_name = "blog/blog_category.html"

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(categories__slug=self.kwargs["slug"])
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["category"] = Category.objects.get(slug=self.kwargs["slug"])
        return context


class PostDetailView(FormMixin, DetailView):
    template_name = "blog/post_detail.html"
    model = Post
    context_object_name = "post"
    form_class = CommentForm

    def get_success_url(self):
        return reverse("blog:post-detail", kwargs={"slug": self.object.slug})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["comments"] = Comment.objects.filter(post=self.get_object()).order_by("-created")
        context["form"] = CommentForm(initial={"post": self.object})
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

apps/blog/templates/blog/blog.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}Blog{% endblock %}
{% block content %}
    <main>

        <section class="py-5 text-center container">
            <div class="row py-lg-5">
                <div class="col-lg-6 col-md-8 mx-auto">
                    <h1 class="fw-light">{% trans "Blog page" %}</h1>
                </div>
            </div>
        </section>

        <div class="container">
            <div class="row">
                <div class="col-lg-9">
                    {% for post in posts %}
                        <article>
                            <h4>{{ post.title }}</h4>
                            <p>{{ post.description }}</p>
                        </article>
                        <p class="text-end">
                            <a class="btn btn-primary" href="{% url 'blog:post-detail' post.slug %}">Read more</a>
                        </p>
                        <hr>
                    {% endfor %}
                    <div class="pagination">
                        <span class="step-links">
                            {% if page_obj.has_previous %}
                                <a href="?page=1">&laquo; first</a>
                                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                            {% endif %}

                            <span class="current">
                                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                            </span>

                            {% if page_obj.has_next %}
                                <a href="?page={{ page_obj.next_page_number }}">next</a>
                                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                            {% endif %}
                        </span>
                    </div>
                </div>
                <div class="col-lg-3">
                    <aside>
                        <h4>{% trans "Categories" %}</h4>
                        <ul class="list-group">
                            {% for category in categories %}
                                <li class="list-group-item">
                                    <a href="{% url 'blog:blog-category' category.slug %}">{{ category.title }}
                                        ({{ category.posts_count }})
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                    </aside>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

apps/blog/templates/blog/blog_category.html
{% extends 'base.html' %}
{% block title %}Blog - Category{% endblock %}
{% block content %}
    <main>

        <section class="py-5 text-center container">
            <div class="row py-lg-5">
                <div class="col-lg-6 col-md-8 mx-auto">
                    <h1 class="fw-light">Category: {{ category.title }}</h1>
                </div>
            </div>
        </section>

        <div class="container">
            <div class="row">
                <div class="col-lg-9">
                    {% for post in posts %}
                        <article>
                            <h4>{{ post.title }}</h4>
                            <p>{{ post.description }}</p>
                        </article>
                        <p class="text-end">
                            <a class="btn btn-primary" href="{% url 'blog:post-detail' post.slug %}">Read more</a>
                        </p>
                        <hr>
                    {% endfor %}
                    <div class="pagination">
                        <span class="step-links">
                            {% if page_obj.has_previous %}
                                <a href="?page=1">&laquo; first</a>
                                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                            {% endif %}

                            <span class="current">
                                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                            </span>

                            {% if page_obj.has_next %}
                                <a href="?page={{ page_obj.next_page_number }}">next</a>
                                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                            {% endif %}
                        </span>
                    </div>
                </div>
                <div class="col-lg-3">
                    <aside>
                        <h4>Categories</h4>
                        <ul class="list-group">
                            {% for category in categories %}
                                <li class="list-group-item">
                                    <a href="{% url 'blog:blog-category' category.slug %}">{{ category.title }}
                                        ({{ category.posts_count }})</a>
                                </li>
                            {% endfor %}
                        </ul>
                    </aside>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

apps/blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
    <main>

        <section class="py-5 text-center container">
            <div class="row py-lg-5">
                <div class="col-lg-6 col-md-8 mx-auto">
                    <h1 class="fw-light">Blog example</h1>
                </div>
            </div>
        </section>

        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <article>
                        <h4>{{ post.title }}</h4>
                        <p>{{ post.description }}</p>
                    </article>
                    <h3 class="mt-5 mb-3">Comment form</h3>
                    <form method="post">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button class="btn btn-primary" type="submit">Submit</button>
                    </form>
                    <h3 class="mt-5 mb-3">Comments</h3>

                    {% if not comments %}
                        <div class="alert alert-info">
                            There are no comments yet.
                        </div>
                    {% endif %}
                    {% for comment in comments %}
                        <div class="card mb-3">
                            <div class="card-body"><strong>{{ comment.author }}: </strong>{{ comment.text }}<br><br>
                                <div class="text-end">
                                    {{ comment.created }}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </main>
{% endblock %}